#!/bin/bash

# just build
cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -O3 -flto -fno-gcse -fno-ident -fno-asynchronous-unwind-tables -ffunction-sections -Wl,--gc-sections"
cmake --build build --config Release

# compressing binary
if command -p which upx; then
	echo "UPX found, proceeding to compress the binary..."
	upx --overlay=strip --best --compress-icons=3 --no-reloc --all-methods --all-filters --no-lzma build/paclogger
else
	echo "UPX not found."
fi

# if user passes -i flag, install
if [[ $1 == "-i" ]]; then
	cmake --install build
fi
