#!/bin/bash

# just build
cmake -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release

# compressing binary
if command -p which upx; then
    echo "UPX found, proceeding to compress the binary..."
    upx --overlay=strip --best --compress-icons=3 --no-reloc --all-methods --all-filters --no-lzma build/paclogger
    exit 0
else
    echo "UPX not found. Exiting..."
    exit 0
fi

# if user passes -i flag, install
if [[ "$1" == "-i" ]]; then
    cmake --install build
fi
